---
- name: install python-apt on ansible < 1.6.0 and ubuntu et al
  sudo: yes
  raw: >
    if command -v apt-get; then
       python -c "import apt" ||
       (command -v apt-get && apt-get install -y python-apt);
    fi

- name: apt-get update
  apt: update_cache=true cache_valid_time=3600
  sudo: yes

- set_fact:
    backcompat_pkg_mgr: '{{ansible_pkg_mgr}}'
