---
- name: install python2-dnf on ansible 2.1/fedora 24
  sudo: yes
  raw: >
    if > /dev/null command -v dnf; then
       python -c "import dnf" ||
       (> /dev/null command -v dnf && dnf install -y python2-dnf);
    fi

- name: detect if dnf exists
  raw: "> /dev/null command -v dnf"
  register: dnf_result
  ignore_errors: True

- set_fact:
    backcompat_pkg_mgr: 'dnf'
  when: dnf_result|success

- set_fact:
    backcompat_pkg_mgr: 'yum'
  when: dnf_result|failed

- name: install python2-dnf on ansible <=1.9.2/fedora 24
  sudo: yes
  raw: >
    if > /dev/null command -v yum && ! > /dev/null command -v dnf; then
       python -c "import yum" ||
       (> /dev/null command -v yum && ! > /dev/null command -v dnf && yum install -y python2-yum);
    fi
